### PR TITLE
Major refactor

### PR DESCRIPTION
**Pull request by hasnainvirk**
@RobMeades Hi Rob, please review this. Please let me know of your views and insights.

### CODE REVIEW

**Comment by hasnainvirk** [comment]
@RobMeades In my humble opion, SystemInit() is the right place to call initialization stuff. The STM fashion has been to poke register directly, but I think we can do better with ublox_mdm* APIs (clarity is an added value with your APIs).  ublox_mdm_init() will be called from systemInit() and our recent changes will make sure that we do not have any effect of zeroing out variables on our stuff.  

Target labels are key words to tell the build system that my specific target, e.g., UBLOX_C030 needs certain target modules located at various places. Consider this as an example. Say we have a label STM, which would mean that my target belongs to a family called STM so include stuff from that directory. Another label STM32F would pin us down to F4 family. UBLOX_MODEM is also a label like the ones described before. However, location of TARGET_UBLOX_MODEM is inside 'cellular' directory. When we define our target say 'UBLOX_C030', build system looks for the labels and gathers the stuff we need, e.g., things from TARGET_STM32F4 directory (label was STM32F4), things from TARGET_UBLOX_MODEM (label was UBLOX_MODEM) which happens to exist in a different location inside the tree.

**Comment by hasnainvirk** [comment]
Modem driver that will be fetched using UBLOX_MODEM label, is shared between C027 and C030.
We don't need to do ifdef in the driver until unless we have common ublox_mdm_* APIs. 
I have tested stuff with C027 with tis configuration. I think you can test with C030. Only thing remaining in 'todo' is to actually call ublox_mdm_init() from SystemInit() for C030.

**Comment by RobMeades** [comment]
Oh, I see, I'd not spotted that this is now a common Celllular API driver to all u-blox modems on both board types.  I think that's a good step, but it does raise the question of regression test because now any change I make on C030 can have an adverse effect on C027.  I don't actually have a proper C027 (just a variant of my own) and there are none in the ARM CI system.  We desperately need to fix that.

I don't understand what you mean by "do not have any effect of zeroing out variables on our stuff".  What change have you made to prevent variables being zeroed after the call to SystemInit() on STM platforms?

On more thing: is there a reason for the ugly "goto" and the like in the Cellular driver?  It is somewhat unconventional code for no reason that I can see, and I was planning to not have it that way in the C030 driver.

**Comment by hasnainvirk** [comment]
@RobMeades :) gotos are fine if handled with care especially in error cases. However, if you don't like that style please go ahead and replace according to your taste. Its our driver, not only mine :D .. 
in ublox_low_level_api, you can see that we have removed static variables which were being used inside the functions. These variables were getting zeroed out after systemInit() because of _start function.  I did changed the behaviour for C027 case but I left ublox_low_level_api for C030 partially done. My mistake. Please go ahead and change the ublox_low_level_api inside TARGET_UBLOX_C030 according to the one in TARGET_UBLOX_C027. Actually I can do it for you as I started this thread. Then you can add or remove stuff as you please.

**Comment by RobMeades** [comment]
I prefer to stay away from unusual constructs, keep my code boring, tell stories in comments, that kinda guy, mostly 'cos I can never remember one week what code crimes I committed the previous week :-).
Understood on the removal of the static variables.  Shall I press the merge button, or will you?

**Comment by hasnainvirk** [comment]
You can. I think you can gothrough the ublox_low_level_api code in TARGET_UBLOX_C030 also better than me. As I am not sure how the hardware is wired up. 

Point take, I will try to use normal construct in my feature branch with unusually detailed stories :) . by the way I took the liberty to cherry-pick this commit on top of my feature branch. We are soon going to start (epochs long:D, world war like) merge process to master for my feature branch. 

For the CI, I am pulling all the stringswithing my reach from the confines of my desk ofcourse to kick start a cellular-minimal-example which would run in our testing harness with just bringing up the network, i.e., a minimal test to mark health of the platform. Unfortunately, despite my valiant efforts, I could not fit our full testing harness app for C027 because of limited RAM (I can only play with 32K). Solutions to steal at least 16K of RAM from ethernet were proven to be futile as they were not portable. :( I hope you understand. Somebody needs to sit down and make the memory map automatic.

**Comment by RobMeades** [comment]
Button pressed.  I'll give it a go on my C030 board next (I've borrowed one that has a working modem).  Understood on the RAM thing, not too much that can be done there unfortunately, apart from deprecate C027 once C030 is flying off the shelves.

**Comment by hasnainvirk** [comment]
Sounds empowering :) .. Awesome !

**Pull request merged**
